name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

env:
  FORCE_COLOR: 3 # Diplay colors

jobs:
  ci:
    name: Integration
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Run tests
        run: pnpm run test
      - name: Build all packages
        run: pnpm build


